language: r
warnings_are_errors: true
bioc_required: true
sudo: required

r_github_packages:
    - hadley/testthat
    - jimhester/covr

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library(covr);coveralls()'
